name: CD
concurrency:
  group: ${{github.workflow}}-${{github.ref || github.run_id}}
  cancel-in-progress: true
on:
  push:
    branches:
      - "master"
permissions:
  contents: write
  actions: read
jobs:
  cd:
    name: SSH to server and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Extract matadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: xuananhdocker/website
          tags: |
            type=raw,value={{date 'YYYY-MM-DD'}}
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST}}
          username: ubuntu
          key: ${{secrets.SSH_PRIV_KEY}}
          port: 22
          script: |
            cd /home/ubuntu/crawler-demo
            sh deploy.sh xuananhdocker/website ${{steps.meta.outputs.tags}}
